plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jlxc.uvcai'
    compileSdk 35

    defaultConfig {
        applicationId "com.jlxc.uvcai"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0-direct-uvc"

        ndk {
            // 你的车机疑似 32 位，先只出 32 位 APK，避免装错 ABI。
            abiFilters "armeabi-v7a"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.herohan:UVCAndroid:1.0.12'
}
